---
- hosts: tomc
  become: true
  tasks:
    - name: copy war to server i am deploying to
      copy:
        src:  /var/lib/jenkins/workspace/TEST3/build/app/PKG-00.pkg
        dest: /home/ansadmin/moDest
